allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 2890
  server: 160.16.63.16
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 295.7
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 3.112.229.1
  speed: 290.22
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 59.125.62.188
  speed: 288.83
  type: ss
- flow: xtls-rprx-vision
  name: US_speednode_0028
  port: 443
  reality-opts:
    public-key: VA5-XSH73WyopK0i8jc2i-23N0VPVwmN8w7TX1MnVyg
    short-id: 9df18b8856e52959
  server: 185.177.238.80
  servername: nl3.truservice.top
  skip-cert-verify: false
  speed: 287.31
  tls: true
  type: vless
  udp: true
  uuid: 1762a070-294a-4999-9c59-05aa4922feed
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 160.16.63.16
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 277.54
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0015
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 261.31
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: DE_speednode_0004
  port: 29973
  reality-opts:
    public-key: QqNYhBZPJmHBGFF_4WsxNPcH8xve-4gma9--drcflHQ
    short-id: cd6229f31e7180e6
  server: 185.161.251.24
  servername: yandex.ru
  skip-cert-verify: false
  speed: 253.24
  tls: true
  type: vless
  udp: true
  uuid: a1493ccd-d1a4-4087-9041-1b3500224003
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 243.83
  tls: false
  type: hysteria2
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 153.121.65.107
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 228.24
  type: trojan
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 18.163.122.76
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 217.95
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0017
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: 5.129.252.60
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 212.84
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 8112
  server: 35.77.94.201
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 149.06
  type: trojan
- name: MCI-@V2rayAlpha--2
  password: 2b67ONZROv+fRVMxB94BSw==
  port: 443
  server: 5.231.70.79
  skip-cert-verify: true
  sni: bing.com
  speed: 148.12
  tls: false
  type: hysteria2
- name: RU_speednode_0016
  network: ws
  password: -4146XJHYAzJ4K8Ov6_LBQ
  port: 11000
  server: 194.35.116.62
  skip-cert-verify: false
  sni: f4e23c6c168f0e91.noproblemvpn.ru
  speed: 137.96
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: f4e23c6c168f0e91.noproblemvpn.ru
    path: /tw
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 134.05
  tls: false
  type: hysteria2
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 131.66
  tls: false
  type: hysteria2
- client-fingerprint: firefox
  name: DE_speednode_0002
  port: 9107
  reality-opts:
    public-key: Go_wk-NFoenM3xuCSQ84_0Lzh3Y6XrHzTz8XTbQl8lI
    short-id: e8ef8df79e4a6343
  server: 195.254.165.152
  servername: refersion.com
  skip-cert-verify: false
  speed: 124.39
  tls: true
  type: vless
  udp: true
  uuid: 774727ed-1e56-41bd-b55f-28549e21bcc8
- flow: xtls-rprx-vision
  name: US_speednode_0026
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 121.48
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 115.08
  tls: false
  type: hysteria2
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - ç¾å›½|@ripaojiedian
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - US_speednode_0028
  - æ—¥æœ¬3|@ripaojiedian
  - RU_speednode_0015
  - DE_speednode_0004
  - '@NoForcedheaven'
  - æ—¥æœ¬2|@ripaojiedian
  - ç¾å›½3|@ripaojiedian
  - RU_speednode_0017
  - æ—¥æœ¬|@ripaojiedian
  - MCI-@V2rayAlpha--2
  - RU_speednode_0016
  - MCI-IR--@V2rayAlpha-14
  - '@V2rayNG3'
  - DE_speednode_0002
  - US_speednode_0026
  - MCI-IR--@V2rayAlpha-7
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
