allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 280.81
  type: trojan
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 5156
  server: 153.121.65.212
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 275.69
  type: trojan
- name: HK_speednode_0013
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me/ripaojiedian
  speed: 268.37
  type: trojan
  udp: true
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 2760
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 268.02
  type: trojan
- name: RU_speednode_0016
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 244.96
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 3127
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 201.44
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 197.64
  tls: false
  type: hysteria2
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 182.49
  tls: false
  type: hysteria2
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 155.39
  type: trojan
- name: HK_speednode_0012
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 142.96
  type: trojan
  udp: true
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯6|@ripaojiedian
  password: asd123456
  port: 8388
  server: 103.149.183.191
  speed: 124.24
  type: ss
- flow: xtls-rprx-vision
  name: GB_speednode_0006
  port: 443
  reality-opts:
    public-key: Mn0DIMKW6zu0_D3E1qKO7xMlIVZvB-rqO_-f7Le2vAs
    short-id: 428ef87fd47a3a32
  server: nl.nodes.rocketnetwork.ru
  servername: nl.nodes.rocketnetwork.ru
  skip-cert-verify: false
  speed: 101.92
  tls: true
  type: vless
  udp: true
  uuid: bccbecc9-c1d2-45d1-b3fa-771a19b9831c
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - æ—¥æœ¬2|@ripaojiedian
  - æ—¥æœ¬|@ripaojiedian
  - HK_speednode_0013
  - æ–°åŠ å¡|@ripaojiedian
  - RU_speednode_0016
  - æ–°åŠ å¡3|@ripaojiedian
  - '@V2rayNG3'
  - MCI-IR--@V2rayAlpha-14
  - é¦™æ¸¯5|@ripaojiedian
  - HK_speednode_0012
  - ğŸ‡­ğŸ‡° é¦™æ¸¯6|@ripaojiedian
  - GB_speednode_0006
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
