allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.131.243
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 292.68
  type: trojan
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4054
  server: 153.121.76.9
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 276.51
  type: trojan
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 260.92
  type: trojan
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 16.162.87.79
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 215.21
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0001
  port: 26861
  reality-opts:
    public-key: IIdE2p3vqHDjHfLrvJXkrLoYpYMJH0R1tacCkHiDtAA
    short-id: ecc1c4
  server: shadowshaman.fonixapp.org
  servername: groww.in
  skip-cert-verify: false
  speed: 178.02
  tls: true
  type: vless
  udp: true
  uuid: 04db6938-72dc-42b4-a096-cc6a5e8316d2
- flow: xtls-rprx-vision
  name: LB_speednode_0011
  port: 443
  reality-opts:
    public-key: -Bdu8i-HU28Xmx87RMou5okYo8TqfbyZ8Ufs9RodUGE
    short-id: 097de35e52ec5256
  server: 77.110.127.105
  servername: st.ozone.ru
  skip-cert-verify: false
  speed: 167.78
  tls: true
  type: vless
  udp: true
  uuid: 72239cbc-5a25-411c-b4f5-b9167a10f5e1
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.53
  speed: 167.05
  type: ss
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 152.84
  tls: false
  type: hysteria2
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 150.14
  tls: false
  type: hysteria2
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - æ—¥æœ¬2|@ripaojiedian
  - ç¾å›½|@ripaojiedian
  - é¦™æ¸¯5|@ripaojiedian
  - ç¾å›½3|@ripaojiedian
  - AT_speednode_0001
  - LB_speednode_0011
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - '@V2rayNG3'
  - '@NoForcedheaven'
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
