allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 日本3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 153.121.39.240
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 285.47
  type: trojan
- name: 日本2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3169
  server: 160.16.138.24
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 249.31
  type: trojan
- name: PL_speednode_0022
  network: ws
  password: 422d402c-58f1-4473-abeb-fe6e69dc97ed
  port: 8443
  server: 217.30.10.31
  skip-cert-verify: false
  sni: joss.gpj1.web.id
  speed: 243.26
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj1.web.id
    path: /Free-VPN-CF-Geo-Project/217.30.10.31=8443
- name: ES_speednode_0008
  network: ws
  password: 1e1a7efa-a4f1-4936-a470-a001e0c3c85b
  port: 8443
  server: 212.227.144.37
  skip-cert-verify: false
  sni: joss.gpj1.web.id
  speed: 234.23
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj1.web.id
    path: /Free-VPN-CF-Geo-Project/212.227.144.37=8443
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 211.05
  tls: false
  type: hysteria2
- name: FR_speednode_0011
  network: ws
  password: e6f0e8b0-3dc5-4d53-a23a-86c02d5ba098
  port: 443
  server: 51.15.210.1
  skip-cert-verify: false
  sni: joss.gpj1.web.id
  speed: 208.83
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj1.web.id
    path: /Free-VPN-CF-Geo-Project/51.15.210.1=443
- name: IL_speednode_0014
  network: ws
  password: 8f58ba37-a117-4ad3-9422-37b62e01d2e6
  port: 443
  server: 77.91.74.6
  skip-cert-verify: false
  sni: joss.gpj1.web.id
  speed: 204.68
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj1.web.id
    path: /Free-VPN-CF-Geo-Project/77.91.74.6=443
- client-fingerprint: ios
  flow: xtls-rprx-vision
  name: IR_speednode_0016
  port: 18000
  reality-opts:
    public-key: hlRqquCI6AiCSbifwaNIlf_fVoHols95S2A1OG8xnVk
  server: hl.kunlun01.com
  servername: s0.awsstatic.com
  skip-cert-verify: false
  speed: 183.35
  tls: true
  type: vless
  udp: true
  uuid: 2f1b82ea-7186-4655-88d3-b06478519fef
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 151.52
  tls: false
  type: hysteria2
- http-opts:
    headers:
      Host:
      - Telewebion.com
    method: GET
    path:
    - /
  name: IR_speednode_0017
  network: http
  port: 20532
  server: 94.182.137.12
  servername: Telewebion.com
  skip-cert-verify: false
  speed: 150.08
  tls: false
  type: vless
  udp: true
  uuid: 8496c102-4094-4dd3-ad63-7bb7a35cbaee
- name: 新加坡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 381
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 147.95
  type: trojan
- client-fingerprint: ios
  flow: xtls-rprx-vision
  name: TW_speednode_0027
  port: 14090
  reality-opts:
    public-key: hlRqquCI6AiCSbifwaNIlf_fVoHols95S2A1OG8xnVk
  server: tw.kunlun01.com
  servername: s0.awsstatic.com
  skip-cert-verify: false
  speed: 131.76
  tls: true
  type: vless
  udp: true
  uuid: 2f1b82ea-7186-4655-88d3-b06478519fef
- flow: xtls-rprx-vision
  name: RU_speednode_0025
  port: 51224
  reality-opts:
    public-key: DvKMFkm82Jkp6Jk_7pXYb0fMXq1MsLMNxDeQfcCSbEA
    short-id: ab12cd34
  server: ru-msk.shvurgceo.online
  servername: download.max.ru
  skip-cert-verify: false
  speed: 130.85
  tls: true
  type: vless
  udp: true
  uuid: 14305246-dc93-4b3c-9f6c-d0b29fa7e4fa
- name: TW_speednode_0026
  password: exaxgqkKkd0TAMrCxeonWg==
  port: 1443
  server: twmoon1-cdn-route.couldflare-cdn.com
  speed: 120.79
  tls: true
  type: http
  udp: true
  username: mrwdfNTD8M79LCukCieldrqZWqs=
- name: US_speednode_0029
  network: ws
  port: 80
  server: www.speedtest.net
  servername: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
  skip-cert-verify: false
  speed: 105.34
  tls: false
  type: vless
  udp: true
  uuid: e1f6bc5b-cbc2-49bb-8f26-1bf8bb85d18a
  ws-opts:
    headers:
      Host: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
    path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
- name: RU_speednode_0024
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 102.38
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
proxy-groups:
- name: 自动选择
  proxies:
  - 日本3|@ripaojiedian
  - 日本2|@ripaojiedian
  - PL_speednode_0022
  - ES_speednode_0008
  - MCI-IR--@V2rayAlpha-14
  - FR_speednode_0011
  - IL_speednode_0014
  - IR_speednode_0016
  - '@V2rayNG3'
  - IR_speednode_0017
  - 新加坡3|@ripaojiedian
  - TW_speednode_0027
  - RU_speednode_0025
  - TW_speednode_0026
  - US_speednode_0029
  - RU_speednode_0024
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
