allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 美国2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.70.180
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 275.31
  type: trojan
- name: 香港4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 267.33
  type: trojan
- name: IL_speednode_0006
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 45.144.172.243
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 249.1
  type: trojan
  udp: true
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 246.3
  tls: false
  type: hysteria2
- name: 美国|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.70.180
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 240.54
  type: trojan
- name: 日本|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4492
  server: 160.16.85.138
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 238.26
  type: trojan
- name: CH_speednode_0001
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 194.87.18.124
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 232.75
  type: trojan
  udp: true
- name: 日本3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3093
  server: 160.16.150.76
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 230.49
  type: trojan
- name: 新加坡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 219.65
  type: trojan
- name: 新加坡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 160.16.116.227
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 153.08
  type: trojan
- flow: xtls-rprx-vision
  name: GB_speednode_0005
  port: 443
  reality-opts:
    public-key: Mn0DIMKW6zu0_D3E1qKO7xMlIVZvB-rqO_-f7Le2vAs
    short-id: 428ef87fd47a3a32
  server: nl.nodes.rocketnetwork.ru
  servername: nl.nodes.rocketnetwork.ru
  skip-cert-verify: false
  speed: 153.02
  tls: true
  type: vless
  udp: true
  uuid: bccbecc9-c1d2-45d1-b3fa-771a19b9831c
- name: RU_speednode_0012
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 146.73
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: 新加坡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 138.85
  type: trojan
- name: 日本2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 112.76
  type: trojan
proxy-groups:
- name: 自动选择
  proxies:
  - 美国2|@ripaojiedian
  - 香港4|@ripaojiedian
  - IL_speednode_0006
  - '@NoForcedheaven'
  - 美国|@ripaojiedian
  - 日本|@ripaojiedian
  - CH_speednode_0001
  - 日本3|@ripaojiedian
  - 新加坡3|@ripaojiedian
  - 新加坡2|@ripaojiedian
  - GB_speednode_0005
  - RU_speednode_0012
  - 新加坡|@ripaojiedian
  - 日本2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
