allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.70.180
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 280.33
  type: trojan
- name: é¦™æ¸¯4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 278.4
  type: trojan
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 160.16.116.227
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 256.56
  type: trojan
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.225
  speed: 252.75
  type: ss
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 221.53
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 190.47
  tls: false
  type: hysteria2
- name: RU_speednode_0012
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 159.44
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 129.33
  type: trojan
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3093
  server: 160.16.150.76
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 128.24
  type: trojan
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4492
  server: 160.16.85.138
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 125.37
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - ç¾å›½2|@ripaojiedian
  - é¦™æ¸¯4|@ripaojiedian
  - æ–°åŠ å¡2|@ripaojiedian
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - é¦™æ¸¯5|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - RU_speednode_0012
  - æ–°åŠ å¡3|@ripaojiedian
  - æ—¥æœ¬3|@ripaojiedian
  - æ—¥æœ¬|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
