allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 1334
  server: 160.16.57.238
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 276.91
  type: trojan
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 38.180.191.251
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 229.18
  type: trojan
- name: RU_speednode_0016
  network: ws
  password: -4146XJHYAzJ4K8Ov6_LBQ
  port: 11000
  server: 194.35.116.62
  skip-cert-verify: false
  sni: f4e23c6c168f0e91.noproblemvpn.ru
  speed: 219.98
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: f4e23c6c168f0e91.noproblemvpn.ru
    path: /tw
- flow: xtls-rprx-vision
  name: RU_speednode_0017
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: 5.129.252.60
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 216.03
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- client-fingerprint: firefox
  name: DE_speednode_0002
  port: 9107
  reality-opts:
    public-key: Go_wk-NFoenM3xuCSQ84_0Lzh3Y6XrHzTz8XTbQl8lI
    short-id: e8ef8df79e4a6343
  server: 195.254.165.152
  servername: refersion.com
  skip-cert-verify: false
  speed: 211.35
  tls: true
  type: vless
  udp: true
  uuid: 774727ed-1e56-41bd-b55f-28549e21bcc8
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 153.121.51.29
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 207.44
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 172.105.217.136
  speed: 189.54
  type: ss
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.57.238
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 187.92
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 159.96
  tls: false
  type: hysteria2
- name: DE_speednode_0004
  port: 29973
  reality-opts:
    public-key: QqNYhBZPJmHBGFF_4WsxNPcH8xve-4gma9--drcflHQ
    short-id: cd6229f31e7180e6
  server: 185.161.251.24
  servername: yandex.ru
  skip-cert-verify: false
  speed: 148.29
  tls: true
  type: vless
  udp: true
  uuid: a1493ccd-d1a4-4087-9041-1b3500224003
- flow: xtls-rprx-vision
  name: US_speednode_0028
  port: 443
  reality-opts:
    public-key: VA5-XSH73WyopK0i8jc2i-23N0VPVwmN8w7TX1MnVyg
    short-id: 9df18b8856e52959
  server: 185.177.238.80
  servername: nl3.truservice.top
  skip-cert-verify: false
  speed: 147.51
  tls: true
  type: vless
  udp: true
  uuid: 1762a070-294a-4999-9c59-05aa4922feed
- flow: xtls-rprx-vision
  name: US_speednode_0026
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 130.09
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 130.02
  tls: false
  type: hysteria2
- name: US_speednode_0030
  network: ws
  port: 80
  server: www.speedtest.net
  servername: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
  skip-cert-verify: false
  speed: 126.97
  tls: false
  type: vless
  udp: true
  uuid: f8f19bc7-54c1-4612-9cff-4ce3852d2bba
  ws-opts:
    headers:
      Host: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
    path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 60.249.35.3
  speed: 124.23
  type: ss
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 1924
  server: 160.16.227.93
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 123.79
  type: trojan
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 121.94
  tls: false
  type: hysteria2
- name: All-@V2rayAlpha--44
  password: 862e90e1-2f26-4506-b8b9-0adf20da05fc
  port: 47262
  server: 40.233.103.51
  skip-cert-verify: true
  sni: www.bing.com
  speed: 115.01
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: US_speednode_0023
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: fis.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 114.56
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4569
  server: us.wyau.cn
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 113.68
  type: trojan
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 202.181.103.235
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 113.67
  type: trojan
- name: MCI-@V2rayAlpha--2
  password: 2b67ONZROv+fRVMxB94BSw==
  port: 443
  server: 5.231.70.79
  skip-cert-verify: true
  sni: bing.com
  speed: 110.41
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: RU_speednode_0015
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 109.46
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: é¦™æ¸¯3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 443
  server: 58.152.110.216
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 108.19
  type: trojan
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5552
  server: 160.16.236.32
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 106.8
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - æ—¥æœ¬2|@ripaojiedian
  - æ–°åŠ å¡3|@ripaojiedian
  - RU_speednode_0016
  - RU_speednode_0017
  - DE_speednode_0002
  - æ–°åŠ å¡2|@ripaojiedian
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - ç¾å›½2|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - DE_speednode_0004
  - US_speednode_0028
  - US_speednode_0026
  - '@NoForcedheaven'
  - US_speednode_0030
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - æ—¥æœ¬|@ripaojiedian
  - MCI-IR--@V2rayAlpha-7
  - All-@V2rayAlpha--44
  - US_speednode_0023
  - ç¾å›½3|@ripaojiedian
  - æ—¥æœ¬3|@ripaojiedian
  - MCI-@V2rayAlpha--2
  - RU_speednode_0015
  - é¦™æ¸¯3|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
