allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- flow: xtls-rprx-vision
  name: AT_speednode_0004
  port: 31502
  reality-opts:
    public-key: oenAlMhG602prGwOqnAt5yZ55yuDEfZwGZXn-WaxizM
    short-id: e1814a
  server: silverzebra.fonixapp.org
  servername: marmiton.org
  skip-cert-verify: false
  speed: 287.13
  tls: true
  type: vless
  udp: true
  uuid: b20c12e7-f071-4829-94e7-17dc4e43a37a
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 280.95
  type: trojan
- flow: xtls-rprx-vision
  name: DE_speednode_0005
  port: 22155
  reality-opts:
    public-key: DWplnF7h0HInlj88rSKUTwBti6hH_yFhxEtX3TKZn08
    short-id: 9ec128
  server: facelessvoid.fonixapp.org
  servername: steampowered.com
  skip-cert-verify: false
  speed: 244.65
  tls: true
  type: vless
  udp: true
  uuid: 1d83ca4e-9708-4338-b177-403aa258488b
- alterId: 2
  cipher: auto
  name: é¦™æ¸¯|@ripaojiedian
  network: ws
  port: '30809'
  server: v9.heduian.link
  servername: ''
  skip-cert-verify: false
  speed: 228.35
  tls: false
  type: vmess
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-opts:
    headers:
      Host: baidu.com
    path: /oooo
- alterId: 0
  cipher: auto
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  port: 15003
  server: 178.157.57.166
  skip-cert-verify: false
  speed: 222.74
  tls: false
  type: vmess
  uuid: edf4c847-3164-4d63-ab9b-c98acba96f1e
- flow: xtls-rprx-vision
  name: AT_speednode_0002
  port: 12645
  reality-opts:
    public-key: U15vYKJBiI0x1Sltv3qZrtuRoGlw5fIu-jlHfN1hBB4
    short-id: 3fd623
  server: graygoat.fonixapp.org
  servername: smallpdf.com
  skip-cert-verify: false
  speed: 217.4
  tls: true
  type: vless
  udp: true
  uuid: 8d5bca78-f49f-4e49-ad7b-bb58da44d40b
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 213.07
  tls: false
  type: hysteria2
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.70.180
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 204.89
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0003
  port: 27274
  reality-opts:
    public-key: tK-R4w5CsF0DSBD0ycQcRQLKgYqOi0TBQFZCHmsaa1Q
    short-id: 992756930320c803
  server: windrunner.fonixapp.org
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 191.06
  tls: true
  type: vless
  udp: true
  uuid: f07cb7d9-36d3-4b65-b4dd-186be58218dd
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 190.39
  tls: false
  type: hysteria2
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.70.180
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 181.48
  type: trojan
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2569
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 171.19
  type: trojan
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 160.16.116.227
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 166.32
  type: trojan
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4492
  server: 160.16.85.138
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 165.52
  type: trojan
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 155.25
  type: trojan
- name: RU_speednode_0013
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 148.91
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 145.84
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 129.26
  tls: false
  type: hysteria2
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 114.81
  type: trojan
- alterId: 0
  cipher: auto
  name: æ—¥æœ¬4|@ripaojiedian
  network: tcp
  port: '15003'
  server: 178.157.57.166
  servername: ''
  speed: 110.7
  tls: false
  type: vmess
  uuid: edf4c847-3164-4d63-ab9b-c98acba96f1e
- flow: xtls-rprx-vision
  name: LB_speednode_0012
  port: 443
  reality-opts:
    public-key: hnec5SxCD6Os-u0FNi_YS5CML1a_oWb0niZJ1mGuFBo
    short-id: 07e904766d29b958
  server: 77.110.119.225
  servername: st.ozone.ru
  skip-cert-verify: false
  speed: 104.62
  tls: true
  type: vless
  udp: true
  uuid: 4819860c-0e62-4804-9c59-967e5c2bed7a
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - AT_speednode_0004
  - æ—¥æœ¬2|@ripaojiedian
  - DE_speednode_0005
  - é¦™æ¸¯|@ripaojiedian
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - AT_speednode_0002
  - MCI-IR--@V2rayAlpha-14
  - ç¾å›½|@ripaojiedian
  - AT_speednode_0003
  - '@NoForcedheaven'
  - ç¾å›½2|@ripaojiedian
  - ç¾å›½3|@ripaojiedian
  - æ–°åŠ å¡2|@ripaojiedian
  - æ—¥æœ¬|@ripaojiedian
  - é¦™æ¸¯5|@ripaojiedian
  - RU_speednode_0013
  - æ–°åŠ å¡3|@ripaojiedian
  - '@V2rayNG3'
  - æ–°åŠ å¡|@ripaojiedian
  - æ—¥æœ¬4|@ripaojiedian
  - LB_speednode_0012
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
