allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 美国|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.70.180
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 288.12
  type: trojan
- name: 美国3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2569
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 267.56
  type: trojan
- name: 香港5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 259.29
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0004
  port: 31502
  reality-opts:
    public-key: oenAlMhG602prGwOqnAt5yZ55yuDEfZwGZXn-WaxizM
    short-id: e1814a
  server: silverzebra.fonixapp.org
  servername: marmiton.org
  skip-cert-verify: false
  speed: 248.3
  tls: true
  type: vless
  udp: true
  uuid: b20c12e7-f071-4829-94e7-17dc4e43a37a
- name: 香港3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 443
  server: 203.198.122.135
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 228.03
  type: trojan
- flow: xtls-rprx-vision
  name: GR_speednode_0010
  port: 443
  reality-opts:
    public-key: 1pX4yQMG3Gji_VeRpJgZ0dCxHafgiK0ul1_Paje38S4
    short-id: 4395cf86
  server: 185.242.84.182
  servername: vk.cc
  skip-cert-verify: false
  speed: 226.77
  tls: true
  type: vless
  udp: true
  uuid: 3c0e49cb-8940-561a-83b8-1efbb17f7cf7
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 225.48
  tls: false
  type: hysteria2
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 207.61
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: AT_speednode_0002
  port: 12645
  reality-opts:
    public-key: U15vYKJBiI0x1Sltv3qZrtuRoGlw5fIu-jlHfN1hBB4
    short-id: 3fd623
  server: graygoat.fonixapp.org
  servername: smallpdf.com
  skip-cert-verify: false
  speed: 168.29
  tls: true
  type: vless
  udp: true
  uuid: 8d5bca78-f49f-4e49-ad7b-bb58da44d40b
- name: 美国2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.70.180
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 164.48
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0001
  port: 26861
  reality-opts:
    public-key: IIdE2p3vqHDjHfLrvJXkrLoYpYMJH0R1tacCkHiDtAA
    short-id: ecc1c4
  server: shadowshaman.fonixapp.org
  servername: groww.in
  skip-cert-verify: false
  speed: 157.57
  tls: true
  type: vless
  udp: true
  uuid: 04db6938-72dc-42b4-a096-cc6a5e8316d2
- alterId: 0
  cipher: auto
  name: 日本4|@ripaojiedian
  network: tcp
  port: '15003'
  server: 178.157.57.166
  servername: ''
  speed: 151.68
  tls: false
  type: vmess
  uuid: edf4c847-3164-4d63-ab9b-c98acba96f1e
- flow: xtls-rprx-vision
  name: AT_speednode_0003
  port: 27274
  reality-opts:
    public-key: tK-R4w5CsF0DSBD0ycQcRQLKgYqOi0TBQFZCHmsaa1Q
    short-id: 992756930320c803
  server: windrunner.fonixapp.org
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 138.02
  tls: true
  type: vless
  udp: true
  uuid: f07cb7d9-36d3-4b65-b4dd-186be58218dd
- name: 新加坡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 133.83
  type: trojan
- name: 日本3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3093
  server: 160.16.150.76
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 130.06
  type: trojan
- name: 新加坡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 126.24
  type: trojan
- flow: xtls-rprx-vision
  name: LB_speednode_0012
  port: 443
  reality-opts:
    public-key: hnec5SxCD6Os-u0FNi_YS5CML1a_oWb0niZJ1mGuFBo
    short-id: 07e904766d29b958
  server: 77.110.119.225
  servername: st.ozone.ru
  skip-cert-verify: false
  speed: 123.62
  tls: true
  type: vless
  udp: true
  uuid: 4819860c-0e62-4804-9c59-967e5c2bed7a
- name: 新加坡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 160.16.116.227
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 121.3
  type: trojan
- name: RU_speednode_0013
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 116.29
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: GB_speednode_0009
  port: 40721
  reality-opts:
    public-key: TUZgwzcTvoROSbgnqMh3WorXVMxQNIF2zsEM39FQbyk
    short-id: df8611c07d
  server: 140.238.100.35
  servername: yahoo.com
  skip-cert-verify: false
  speed: 103.24
  tls: true
  type: vless
  udp: true
  uuid: bf3e8944-8d26-47de-8748-b9aa74cce974
proxy-groups:
- name: 自动选择
  proxies:
  - 美国|@ripaojiedian
  - 美国3|@ripaojiedian
  - 香港5|@ripaojiedian
  - AT_speednode_0004
  - 香港3|@ripaojiedian
  - GR_speednode_0010
  - MCI-IR--@V2rayAlpha-14
  - '@NoForcedheaven'
  - AT_speednode_0002
  - 美国2|@ripaojiedian
  - AT_speednode_0001
  - 日本4|@ripaojiedian
  - AT_speednode_0003
  - 新加坡|@ripaojiedian
  - 日本3|@ripaojiedian
  - 新加坡3|@ripaojiedian
  - LB_speednode_0012
  - 新加坡2|@ripaojiedian
  - RU_speednode_0013
  - GB_speednode_0009
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
