allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 美国3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4569
  server: us.wyau.cn
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 278.53
  type: trojan
- name: 日本2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 1334
  server: 160.16.57.238
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 261.18
  type: trojan
- name: US_speednode_0030
  network: ws
  port: 80
  server: www.speedtest.net
  servername: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
  skip-cert-verify: false
  speed: 248.32
  tls: false
  type: vless
  udp: true
  uuid: f8f19bc7-54c1-4612-9cff-4ce3852d2bba
  ws-opts:
    headers:
      Host: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
    path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
- name: 新加坡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5552
  server: 160.16.236.32
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 242.56
  type: trojan
- name: 新加坡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 38.180.191.251
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 240.88
  type: trojan
- name: 美国2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.57.238
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 222.94
  type: trojan
- name: 新加坡2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 153.121.51.29
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 219.57
  type: trojan
- name: 日本3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 202.181.103.235
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 185.18
  type: trojan
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 168.0
  tls: false
  type: hysteria2
- name: 香港3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 443
  server: 58.152.110.216
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 138.83
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0017
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: 5.129.252.60
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 137.65
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: 日本|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 1924
  server: 160.16.227.93
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 119.36
  type: trojan
- name: DE_speednode_0004
  port: 29973
  reality-opts:
    public-key: QqNYhBZPJmHBGFF_4WsxNPcH8xve-4gma9--drcflHQ
    short-id: cd6229f31e7180e6
  server: 185.161.251.24
  servername: yandex.ru
  skip-cert-verify: false
  speed: 117.68
  tls: true
  type: vless
  udp: true
  uuid: a1493ccd-d1a4-4087-9041-1b3500224003
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 101.87
  tls: false
  type: hysteria2
proxy-groups:
- name: 自动选择
  proxies:
  - 美国3|@ripaojiedian
  - 日本2|@ripaojiedian
  - US_speednode_0030
  - 新加坡|@ripaojiedian
  - 新加坡3|@ripaojiedian
  - 美国2|@ripaojiedian
  - 新加坡2|@ripaojiedian
  - 日本3|@ripaojiedian
  - '@NoForcedheaven'
  - 香港3|@ripaojiedian
  - RU_speednode_0017
  - 日本|@ripaojiedian
  - DE_speednode_0004
  - '@V2rayNG3'
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
