allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- alpn:
  - h2
  flow: xtls-rprx-vision
  name: GB_speednode_0002
  port: 443
  reality-opts:
    public-key: ckRcueERkPqqjZABwxqni_J_Nbb70Q6k5fEEUAjoImw
  server: 217.154.218.42
  servername: azure.com
  skip-cert-verify: false
  speed: 289.66
  tls: true
  type: vless
  udp: true
  uuid: 0b0b98be-fdaf-40cc-a953-cc4091c838e1
- name: HK_speednode_0003
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 273.21
  type: trojan
  udp: true
- flow: xtls-rprx-vision
  name: BG_speednode_0001
  port: 8443
  reality-opts:
    public-key: aILMLxhAsgJvx7TY3EsxOdmIc1uB0V7aJVIXaKYPPk4
    short-id: 05a8b9980e65114c
  server: de.monkeyisland.life
  servername: de.monkeyisland.life
  skip-cert-verify: false
  speed: 186.19
  tls: true
  type: vless
  udp: true
  uuid: df5fc3f7-6b01-489a-a73c-e1297b14a3dd
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 202.181.103.246
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 181.6
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 180.92
  tls: false
  type: hysteria2
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4054
  server: 153.121.76.9
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 169.77
  type: trojan
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 166.72
  tls: false
  type: hysteria2
- name: NL_speednode_0004
  network: ws
  password: e812343b-61a1-46fd-b086-b1395d0eb7de
  port: 443
  server: 89.110.116.141
  skip-cert-verify: false
  sni: joss.gpj.web.id
  speed: 157.59
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj.web.id
    path: /Free-VPN-CF-Geo-Project/89.110.116.141=443
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 16.162.87.79
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 153.87
  type: trojan
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.53
  speed: 149.14
  type: ss
- name: é¦™æ¸¯3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 443
  server: 203.198.122.135
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 130.1
  type: trojan
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.131.243
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 129.82
  type: trojan
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 202.181.103.246
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 104.28
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - GB_speednode_0002
  - HK_speednode_0003
  - BG_speednode_0001
  - æ—¥æœ¬3|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - ç¾å›½|@ripaojiedian
  - '@NoForcedheaven'
  - NL_speednode_0004
  - ç¾å›½3|@ripaojiedian
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - é¦™æ¸¯3|@ripaojiedian
  - ç¾å›½2|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
