allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 香港5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 275.12
  type: trojan
- name: 新加坡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 153.121.73.102
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 273.54
  type: trojan
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 272.9
  tls: false
  type: hysteria2
- name: 日本3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3169
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 259.2
  type: trojan
- name: 新加坡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 3127
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 255.83
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 241.45
  tls: false
  type: hysteria2
- name: 美国3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2773
  server: 18.162.123.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 232.5
  type: trojan
- name: HK_speednode_0013
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me/ripaojiedian
  speed: 212.78
  type: trojan
  udp: true
- name: 日本2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 172.2
  type: trojan
- name: 新加坡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 2760
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 134.0
  type: trojan
proxy-groups:
- name: 自动选择
  proxies:
  - 香港5|@ripaojiedian
  - 新加坡2|@ripaojiedian
  - '@NoForcedheaven'
  - 日本3|@ripaojiedian
  - 新加坡3|@ripaojiedian
  - '@V2rayNG3'
  - 美国3|@ripaojiedian
  - HK_speednode_0013
  - 日本2|@ripaojiedian
  - 新加坡|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
