allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.225
  speed: 290.24
  type: ss
- name: RU_speednode_0012
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 283.87
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.70.180
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 263.86
  type: trojan
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 218.83
  type: trojan
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 218.35
  type: trojan
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 198.29
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 184.11
  tls: false
  type: hysteria2
- name: é¦™æ¸¯4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 165.94
  type: trojan
- name: CH_speednode_0001
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 194.87.18.124
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 164.51
  type: trojan
  udp: true
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 124.18
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 109.07
  tls: false
  type: hysteria2
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3093
  server: 160.16.150.76
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 103.08
  type: trojan
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4492
  server: 160.16.85.138
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 100.16
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - RU_speednode_0012
  - ç¾å›½|@ripaojiedian
  - æ–°åŠ å¡3|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  - é¦™æ¸¯5|@ripaojiedian
  - '@V2rayNG3'
  - é¦™æ¸¯4|@ripaojiedian
  - CH_speednode_0001
  - æ—¥æœ¬2|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - æ—¥æœ¬3|@ripaojiedian
  - æ—¥æœ¬|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
