allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- flow: xtls-rprx-vision
  name: GB_speednode_0006
  port: 443
  reality-opts:
    public-key: Mn0DIMKW6zu0_D3E1qKO7xMlIVZvB-rqO_-f7Le2vAs
    short-id: 428ef87fd47a3a32
  server: nl.nodes.rocketnetwork.ru
  servername: nl.nodes.rocketnetwork.ru
  skip-cert-verify: false
  speed: 261.29
  tls: true
  type: vless
  udp: true
  uuid: bccbecc9-c1d2-45d1-b3fa-771a19b9831c
- name: 美国2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.117.182
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 195.36
  type: trojan
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 156.08
  tls: false
  type: hysteria2
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 144.21
  tls: false
  type: hysteria2
- name: 新加坡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 153.121.73.102
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 121.91
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 111.23
  tls: false
  type: hysteria2
proxy-groups:
- name: 自动选择
  proxies:
  - GB_speednode_0006
  - 美国2|@ripaojiedian
  - '@NoForcedheaven'
  - '@V2rayNG3'
  - 新加坡2|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
