allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- flow: xtls-rprx-vision
  name: BG_speednode_0001
  port: 8443
  reality-opts:
    public-key: aILMLxhAsgJvx7TY3EsxOdmIc1uB0V7aJVIXaKYPPk4
    short-id: 05a8b9980e65114c
  server: de.monkeyisland.life
  servername: de.monkeyisland.life
  skip-cert-verify: false
  speed: 291.61
  tls: true
  type: vless
  udp: true
  uuid: df5fc3f7-6b01-489a-a73c-e1297b14a3dd
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 252.61
  tls: false
  type: hysteria2
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 153.121.65.107
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 247.4
  type: trojan
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 3579
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 234.5
  type: trojan
- name: HK_speednode_0003
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 174.7
  type: trojan
  udp: true
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 18.163.122.76
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 167.18
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 145.29
  tls: false
  type: hysteria2
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 115.56
  type: trojan
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.151.196
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 112.9
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 59.125.62.188
  speed: 109.42
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 3.112.229.1
  speed: 107.48
  type: ss
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 153.121.65.107
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 105.98
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - BG_speednode_0001
  - MCI-IR--@V2rayAlpha-14
  - æ–°åŠ å¡2|@ripaojiedian
  - æ–°åŠ å¡3|@ripaojiedian
  - HK_speednode_0003
  - ç¾å›½3|@ripaojiedian
  - '@V2rayNG3'
  - é¦™æ¸¯5|@ripaojiedian
  - ç¾å›½2|@ripaojiedian
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - æ—¥æœ¬2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
