allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.131.243
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 284.18
  type: trojan
- flow: xtls-rprx-vision
  name: LB_speednode_0011
  port: 443
  reality-opts:
    public-key: -Bdu8i-HU28Xmx87RMou5okYo8TqfbyZ8Ufs9RodUGE
    short-id: 097de35e52ec5256
  server: 77.110.127.105
  servername: st.ozone.ru
  skip-cert-verify: false
  speed: 251.19
  tls: true
  type: vless
  udp: true
  uuid: 72239cbc-5a25-411c-b4f5-b9167a10f5e1
- flow: xtls-rprx-vision
  name: DE_speednode_0005
  port: 22155
  reality-opts:
    public-key: DWplnF7h0HInlj88rSKUTwBti6hH_yFhxEtX3TKZn08
    short-id: 9ec128
  server: facelessvoid.fonixapp.org
  servername: steampowered.com
  skip-cert-verify: false
  speed: 249.89
  tls: true
  type: vless
  udp: true
  uuid: 1d83ca4e-9708-4338-b177-403aa258488b
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 3579
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 240.75
  type: trojan
- name: é¦™æ¸¯3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 443
  server: 203.198.122.135
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 231.63
  type: trojan
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.53
  speed: 196.4
  type: ss
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 187.45
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: AT_speednode_0003
  port: 27274
  reality-opts:
    public-key: tK-R4w5CsF0DSBD0ycQcRQLKgYqOi0TBQFZCHmsaa1Q
    short-id: 992756930320c803
  server: windrunner.fonixapp.org
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 184.45
  tls: true
  type: vless
  udp: true
  uuid: f07cb7d9-36d3-4b65-b4dd-186be58218dd
- flow: xtls-rprx-vision
  name: GR_speednode_0010
  port: 443
  reality-opts:
    public-key: 1pX4yQMG3Gji_VeRpJgZ0dCxHafgiK0ul1_Paje38S4
    short-id: 4395cf86
  server: 185.242.84.182
  servername: vk.cc
  skip-cert-verify: false
  speed: 164.56
  tls: true
  type: vless
  udp: true
  uuid: 3c0e49cb-8940-561a-83b8-1efbb17f7cf7
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 202.181.103.246
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 142.7
  type: trojan
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4054
  server: 153.121.76.9
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 131.44
  type: trojan
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 16.162.87.79
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 130.35
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0001
  port: 26861
  reality-opts:
    public-key: IIdE2p3vqHDjHfLrvJXkrLoYpYMJH0R1tacCkHiDtAA
    short-id: ecc1c4
  server: shadowshaman.fonixapp.org
  servername: groww.in
  skip-cert-verify: false
  speed: 117.53
  tls: true
  type: vless
  udp: true
  uuid: 04db6938-72dc-42b4-a096-cc6a5e8316d2
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - æ—¥æœ¬2|@ripaojiedian
  - LB_speednode_0011
  - DE_speednode_0005
  - æ–°åŠ å¡3|@ripaojiedian
  - é¦™æ¸¯3|@ripaojiedian
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - '@NoForcedheaven'
  - AT_speednode_0003
  - GR_speednode_0010
  - æ–°åŠ å¡|@ripaojiedian
  - ç¾å›½|@ripaojiedian
  - ç¾å›½3|@ripaojiedian
  - AT_speednode_0001
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
