allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 美国3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2773
  server: 18.162.123.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 199.99
  type: trojan
- name: 香港4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 189.55
  type: trojan
- name: US_speednode_0014
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 96.126.190.132
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 184.97
  type: trojan
  udp: true
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 169.29
  tls: false
  type: hysteria2
- name: RU_speednode_0012
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 154.23
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 137.94
  tls: false
  type: hysteria2
- name: CH_speednode_0001
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 194.87.18.124
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 112.66
  type: trojan
  udp: true
- flow: xtls-rprx-vision
  name: GB_speednode_0005
  port: 443
  reality-opts:
    public-key: Mn0DIMKW6zu0_D3E1qKO7xMlIVZvB-rqO_-f7Le2vAs
    short-id: 428ef87fd47a3a32
  server: nl.nodes.rocketnetwork.ru
  servername: nl.nodes.rocketnetwork.ru
  skip-cert-verify: false
  speed: 108.52
  tls: true
  type: vless
  udp: true
  uuid: bccbecc9-c1d2-45d1-b3fa-771a19b9831c
proxy-groups:
- name: 自动选择
  proxies:
  - 美国3|@ripaojiedian
  - 香港4|@ripaojiedian
  - US_speednode_0014
  - '@V2rayNG3'
  - RU_speednode_0012
  - '@NoForcedheaven'
  - CH_speednode_0001
  - GB_speednode_0005
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
