allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- flow: xtls-rprx-vision
  name: AT_speednode_0004
  port: 31502
  reality-opts:
    public-key: oenAlMhG602prGwOqnAt5yZ55yuDEfZwGZXn-WaxizM
    short-id: e1814a
  server: silverzebra.fonixapp.org
  servername: marmiton.org
  skip-cert-verify: false
  speed: 295.67
  tls: true
  type: vless
  udp: true
  uuid: b20c12e7-f071-4829-94e7-17dc4e43a37a
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 288.12
  tls: false
  type: hysteria2
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 278.17
  tls: false
  type: hysteria2
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.70.180
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 248.4
  type: trojan
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 160.16.116.227
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 240.28
  type: trojan
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 233.18
  type: trojan
- name: é¦™æ¸¯3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 443
  server: 203.198.122.135
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 227.08
  type: trojan
- flow: xtls-rprx-vision
  name: DE_speednode_0005
  port: 22155
  reality-opts:
    public-key: DWplnF7h0HInlj88rSKUTwBti6hH_yFhxEtX3TKZn08
    short-id: 9ec128
  server: facelessvoid.fonixapp.org
  servername: steampowered.com
  skip-cert-verify: false
  speed: 217.25
  tls: true
  type: vless
  udp: true
  uuid: 1d83ca4e-9708-4338-b177-403aa258488b
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.225
  speed: 215.88
  type: ss
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2569
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 207.23
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0001
  port: 26861
  reality-opts:
    public-key: IIdE2p3vqHDjHfLrvJXkrLoYpYMJH0R1tacCkHiDtAA
    short-id: ecc1c4
  server: shadowshaman.fonixapp.org
  servername: groww.in
  skip-cert-verify: false
  speed: 190.14
  tls: true
  type: vless
  udp: true
  uuid: 04db6938-72dc-42b4-a096-cc6a5e8316d2
- name: GB_speednode_0009
  port: 40721
  reality-opts:
    public-key: TUZgwzcTvoROSbgnqMh3WorXVMxQNIF2zsEM39FQbyk
    short-id: df8611c07d
  server: 140.238.100.35
  servername: yahoo.com
  skip-cert-verify: false
  speed: 181.62
  tls: true
  type: vless
  udp: true
  uuid: bf3e8944-8d26-47de-8748-b9aa74cce974
- alterId: 2
  cipher: auto
  name: é¦™æ¸¯|@ripaojiedian
  network: ws
  port: '30809'
  server: v9.heduian.link
  servername: ''
  skip-cert-verify: false
  speed: 152.04
  tls: false
  type: vmess
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-opts:
    headers:
      Host: baidu.com
    path: /oooo
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.70.180
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 144.84
  type: trojan
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3093
  server: 160.16.150.76
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 139.76
  type: trojan
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 134.29
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0003
  port: 27274
  reality-opts:
    public-key: tK-R4w5CsF0DSBD0ycQcRQLKgYqOi0TBQFZCHmsaa1Q
    short-id: 992756930320c803
  server: windrunner.fonixapp.org
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 133.06
  tls: true
  type: vless
  udp: true
  uuid: f07cb7d9-36d3-4b65-b4dd-186be58218dd
- flow: xtls-rprx-vision
  name: AT_speednode_0002
  port: 12645
  reality-opts:
    public-key: U15vYKJBiI0x1Sltv3qZrtuRoGlw5fIu-jlHfN1hBB4
    short-id: 3fd623
  server: graygoat.fonixapp.org
  servername: smallpdf.com
  skip-cert-verify: false
  speed: 126.27
  tls: true
  type: vless
  udp: true
  uuid: 8d5bca78-f49f-4e49-ad7b-bb58da44d40b
- name: é¦™æ¸¯4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 122.61
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 117.59
  tls: false
  type: hysteria2
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - AT_speednode_0004
  - MCI-IR--@V2rayAlpha-14
  - '@NoForcedheaven'
  - ç¾å›½2|@ripaojiedian
  - æ–°åŠ å¡2|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  - é¦™æ¸¯3|@ripaojiedian
  - DE_speednode_0005
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - ç¾å›½3|@ripaojiedian
  - AT_speednode_0001
  - GB_speednode_0009
  - é¦™æ¸¯|@ripaojiedian
  - ç¾å›½|@ripaojiedian
  - æ—¥æœ¬3|@ripaojiedian
  - æ–°åŠ å¡3|@ripaojiedian
  - AT_speednode_0003
  - AT_speednode_0002
  - é¦™æ¸¯4|@ripaojiedian
  - '@V2rayNG3'
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
