allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 288.88
  tls: false
  type: hysteria2
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 59.125.62.188
  speed: 265.58
  type: ss
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 223.96
  type: trojan
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 220.91
  tls: false
  type: hysteria2
- alpn:
  - h2
  flow: xtls-rprx-vision
  name: GB_speednode_0002
  port: 443
  reality-opts:
    public-key: ckRcueERkPqqjZABwxqni_J_Nbb70Q6k5fEEUAjoImw
  server: 217.154.218.42
  servername: azure.com
  skip-cert-verify: false
  speed: 218.72
  tls: true
  type: vless
  udp: true
  uuid: 0b0b98be-fdaf-40cc-a953-cc4091c838e1
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 153.121.65.107
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 203.05
  type: trojan
- name: 'ğŸ”·ğŸ†”@v2ray_configs_poolğŸ”· #58'
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: tokyo.nezhasu.com
  skip-cert-verify: true
  sni: Tokyo.nezhasu.com
  speed: 202.85
  tls: false
  type: hysteria2
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 160.16.151.196
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 189.83
  type: trojan
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 2890
  server: 160.16.63.16
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 184.91
  type: trojan
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 153.121.65.107
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 157.11
  type: trojan
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 18.163.122.76
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 144.96
  type: trojan
- name: HK_speednode_0003
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 140.47
  type: trojan
  udp: true
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.151.196
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 125.67
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 3.112.229.1
  speed: 100.97
  type: ss
- name: é¦™æ¸¯3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 443
  server: 58.152.110.216
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 100.94
  type: trojan
- name: RU_speednode_0005
  network: ws
  password: 3b38715b-f08a-46dd-9904-7531ca4bb6e8
  port: 2053
  server: 95.182.120.208
  skip-cert-verify: false
  sni: joss.gpj.web.id
  speed: 100.87
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj.web.id
    path: /Free-VPN-CF-Geo-Project/95.182.120.208=2053
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - MCI-IR--@V2rayAlpha-14
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - é¦™æ¸¯5|@ripaojiedian
  - '@NoForcedheaven'
  - GB_speednode_0002
  - æ–°åŠ å¡2|@ripaojiedian
  - 'ğŸ”·ğŸ†”@v2ray_configs_poolğŸ”· #58'
  - æ–°åŠ å¡|@ripaojiedian
  - ç¾å›½|@ripaojiedian
  - æ—¥æœ¬2|@ripaojiedian
  - ç¾å›½3|@ripaojiedian
  - HK_speednode_0003
  - ç¾å›½2|@ripaojiedian
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - é¦™æ¸¯3|@ripaojiedian
  - RU_speednode_0005
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
