allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 160.16.116.227
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 289.01
  type: trojan
- name: IL_speednode_0006
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 45.144.172.243
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 276.28
  type: trojan
  udp: true
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 226.3
  type: trojan
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.225
  speed: 225.06
  type: ss
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 219.31
  type: trojan
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.70.180
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 200.42
  type: trojan
- name: CH_speednode_0001
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 194.87.18.124
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 176.56
  type: trojan
  udp: true
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.70.180
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 161.95
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 153.87
  tls: false
  type: hysteria2
- name: RU_speednode_0012
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 140.52
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4492
  server: 160.16.85.138
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 125.23
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 114.11
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: GB_speednode_0005
  port: 443
  reality-opts:
    public-key: Mn0DIMKW6zu0_D3E1qKO7xMlIVZvB-rqO_-f7Le2vAs
    short-id: 428ef87fd47a3a32
  server: nl.nodes.rocketnetwork.ru
  servername: nl.nodes.rocketnetwork.ru
  skip-cert-verify: false
  speed: 113.44
  tls: true
  type: vless
  udp: true
  uuid: bccbecc9-c1d2-45d1-b3fa-771a19b9831c
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 102.72
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - æ–°åŠ å¡2|@ripaojiedian
  - IL_speednode_0006
  - æ–°åŠ å¡3|@ripaojiedian
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  - ç¾å›½2|@ripaojiedian
  - CH_speednode_0001
  - ç¾å›½|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - RU_speednode_0012
  - æ—¥æœ¬|@ripaojiedian
  - '@V2rayNG3'
  - GB_speednode_0005
  - æ—¥æœ¬2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
