allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 273.03
  tls: false
  type: hysteria2
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 188.99
  tls: false
  type: hysteria2
- name: 新加坡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 3127
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 161.76
  type: trojan
- name: 新加坡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 2760
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 142.58
  type: trojan
- name: 香港5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 117.85
  type: trojan
- name: 日本2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 114.39
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 110.33
  tls: false
  type: hysteria2
- name: 新加坡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 153.121.73.102
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 101.85
  type: trojan
proxy-groups:
- name: 自动选择
  proxies:
  - '@NoForcedheaven'
  - MCI-IR--@V2rayAlpha-14
  - 新加坡3|@ripaojiedian
  - 新加坡|@ripaojiedian
  - 香港5|@ripaojiedian
  - 日本2|@ripaojiedian
  - '@V2rayNG3'
  - 新加坡2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
