allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 日本|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2145
  server: 153.121.53.187
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 283.89
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 267.99
  tls: false
  type: hysteria2
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 250.0
  tls: false
  type: hysteria2
- name: 美国2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.131.243
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 233.48
  type: trojan
- name: 香港4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 229.91
  type: trojan
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 186.65
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: GR_speednode_0010
  port: 443
  reality-opts:
    public-key: 1pX4yQMG3Gji_VeRpJgZ0dCxHafgiK0ul1_Paje38S4
    short-id: 4395cf86
  server: 185.242.84.182
  servername: vk.cc
  skip-cert-verify: false
  speed: 168.33
  tls: true
  type: vless
  udp: true
  uuid: 3c0e49cb-8940-561a-83b8-1efbb17f7cf7
- flow: xtls-rprx-vision
  name: LB_speednode_0012
  port: 443
  reality-opts:
    public-key: hnec5SxCD6Os-u0FNi_YS5CML1a_oWb0niZJ1mGuFBo
    short-id: 07e904766d29b958
  server: 77.110.119.225
  servername: st.ozone.ru
  skip-cert-verify: false
  speed: 164.18
  tls: true
  type: vless
  udp: true
  uuid: 4819860c-0e62-4804-9c59-967e5c2bed7a
- name: RU_speednode_0013
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 144.19
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: 美国3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 16.162.87.79
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 126.13
  type: trojan
proxy-groups:
- name: 自动选择
  proxies:
  - 日本|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - '@V2rayNG3'
  - 美国2|@ripaojiedian
  - 香港4|@ripaojiedian
  - '@NoForcedheaven'
  - GR_speednode_0010
  - LB_speednode_0012
  - RU_speednode_0013
  - 美国3|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
