allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 香港3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 443
  server: 203.198.122.135
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 286.12
  type: trojan
- name: 新加坡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 271.93
  type: trojan
- name: 日本2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 259.17
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0001
  port: 26861
  reality-opts:
    public-key: IIdE2p3vqHDjHfLrvJXkrLoYpYMJH0R1tacCkHiDtAA
    short-id: ecc1c4
  server: shadowshaman.fonixapp.org
  servername: groww.in
  skip-cert-verify: false
  speed: 222.01
  tls: true
  type: vless
  udp: true
  uuid: 04db6938-72dc-42b4-a096-cc6a5e8316d2
- flow: xtls-rprx-vision
  name: LB_speednode_0012
  port: 443
  reality-opts:
    public-key: hnec5SxCD6Os-u0FNi_YS5CML1a_oWb0niZJ1mGuFBo
    short-id: 07e904766d29b958
  server: 77.110.119.225
  servername: st.ozone.ru
  skip-cert-verify: false
  speed: 221.54
  tls: true
  type: vless
  udp: true
  uuid: 4819860c-0e62-4804-9c59-967e5c2bed7a
- name: RU_speednode_0013
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 214.62
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: 美国2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.70.180
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 210.48
  type: trojan
- name: 日本3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3093
  server: 160.16.150.76
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 204.76
  type: trojan
- flow: xtls-rprx-vision
  name: DE_speednode_0005
  port: 22155
  reality-opts:
    public-key: DWplnF7h0HInlj88rSKUTwBti6hH_yFhxEtX3TKZn08
    short-id: 9ec128
  server: facelessvoid.fonixapp.org
  servername: steampowered.com
  skip-cert-verify: false
  speed: 191.42
  tls: true
  type: vless
  udp: true
  uuid: 1d83ca4e-9708-4338-b177-403aa258488b
- name: GB_speednode_0009
  port: 40721
  reality-opts:
    public-key: TUZgwzcTvoROSbgnqMh3WorXVMxQNIF2zsEM39FQbyk
    short-id: df8611c07d
  server: 140.238.100.35
  servername: yahoo.com
  skip-cert-verify: false
  speed: 189.58
  tls: true
  type: vless
  udp: true
  uuid: bf3e8944-8d26-47de-8748-b9aa74cce974
- name: 新加坡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 183.44
  type: trojan
- name: 美国3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2569
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 171.37
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 148.12
  tls: false
  type: hysteria2
- name: 香港5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 131.7
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 128.15
  tls: false
  type: hysteria2
- alterId: 2
  cipher: auto
  name: 香港|@ripaojiedian
  network: ws
  port: '30809'
  server: v9.heduian.link
  servername: ''
  skip-cert-verify: false
  speed: 120.61
  tls: false
  type: vmess
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-opts:
    headers:
      Host: baidu.com
    path: /oooo
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 104.85
  tls: false
  type: hysteria2
proxy-groups:
- name: 自动选择
  proxies:
  - 香港3|@ripaojiedian
  - 新加坡|@ripaojiedian
  - 日本2|@ripaojiedian
  - AT_speednode_0001
  - LB_speednode_0012
  - RU_speednode_0013
  - 美国2|@ripaojiedian
  - 日本3|@ripaojiedian
  - DE_speednode_0005
  - GB_speednode_0009
  - 新加坡3|@ripaojiedian
  - 美国3|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - 香港5|@ripaojiedian
  - '@V2rayNG3'
  - 香港|@ripaojiedian
  - '@NoForcedheaven'
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
