allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: 香港5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 287.34
  type: trojan
- name: 日本2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 248.57
  type: trojan
- name: US_speednode_0014
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 96.126.190.132
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 246.7
  type: trojan
  udp: true
- name: 美国2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.117.182
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 236.19
  type: trojan
- name: 新加坡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 2760
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 219.53
  type: trojan
- flow: xtls-rprx-vision
  name: GB_speednode_0005
  port: 443
  reality-opts:
    public-key: Mn0DIMKW6zu0_D3E1qKO7xMlIVZvB-rqO_-f7Le2vAs
    short-id: 428ef87fd47a3a32
  server: nl.nodes.rocketnetwork.ru
  servername: nl.nodes.rocketnetwork.ru
  skip-cert-verify: false
  speed: 215.99
  tls: true
  type: vless
  udp: true
  uuid: bccbecc9-c1d2-45d1-b3fa-771a19b9831c
- name: 日本3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3169
  server: 160.16.117.182
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 181.91
  type: trojan
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 154.21
  tls: false
  type: hysteria2
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 151.56
  tls: false
  type: hysteria2
- name: 新加坡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 153.121.73.102
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 133.45
  type: trojan
- name: 香港4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 131.74
  type: trojan
- name: IL_speednode_0006
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 45.144.172.243
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 114.92
  type: trojan
  udp: true
- name: RU_speednode_0012
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 109.79
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: 日本|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 5156
  server: 153.121.65.212
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 100.95
  type: trojan
proxy-groups:
- name: 自动选择
  proxies:
  - 香港5|@ripaojiedian
  - 日本2|@ripaojiedian
  - US_speednode_0014
  - 美国2|@ripaojiedian
  - 新加坡|@ripaojiedian
  - GB_speednode_0005
  - 日本3|@ripaojiedian
  - '@NoForcedheaven'
  - MCI-IR--@V2rayAlpha-14
  - 新加坡2|@ripaojiedian
  - 香港4|@ripaojiedian
  - IL_speednode_0006
  - RU_speednode_0012
  - 日本|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
