allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: NL_speednode_0036
  network: ws
  password: 5ad5fe82-6b60-4f59-977b-93910ef7a9ca
  port: 443
  server: 86.107.197.239
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 294.12
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/86.107.197.239=443
- name: Êñ∞Âä†Âù°3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 38.180.191.251
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 275.42
  type: trojan
- flow: xtls-rprx-vision
  name: IL_speednode_0020
  port: 443
  reality-opts:
    public-key: YVDo7U4O-AT2fa5H9E7hyYHKgfZd1vB6UdbAf2ggWQE
    short-id: 55e6af1a35e64a98
  server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
  servername: i2pd.website
  skip-cert-verify: false
  speed: 272.44
  tls: true
  type: vless
  udp: true
  uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
- cipher: chacha20-ietf-poly1305
  name: üáØüáµ Êó•Êú¨4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 172.105.217.136
  speed: 266.75
  type: ss
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 264.34
  tls: false
  type: hysteria2
- name: RU_speednode_0044
  network: ws
  password: 14d6efcf-b0d3-4054-9d4e-e1347e3ceaa2
  port: 2053
  server: 213.159.208.88
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 253.85
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/213.159.208.88=2053
- name: Êó•Êú¨|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 1924
  server: 160.16.227.93
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 245.97
  type: trojan
- name: SE_speednode_0046
  network: ws
  password: edeff73d-065d-4b0a-b848-aad9d3380223
  port: 443
  server: 77.221.141.207
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 238.9
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.221.141.207=443
- flow: xtls-rprx-vision
  name: IQ_speednode_0025
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: frs.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 227.45
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: BG_speednode_0006
  port: 443
  reality-opts:
    public-key: ZmcE7f2ZycnrnsUSPkCrPBIGYC8dM4b27DX47DwCHXk
    short-id: 473915f2ef487f
  server: albania.solobot.ru
  servername: yahoo.com
  skip-cert-verify: false
  speed: 222.36
  tls: true
  type: vless
  udp: true
  uuid: 678bbdc1-7307-4cf2-bec1-bcdbd8efdbe5
- name: IT_speednode_0031
  network: ws
  password: d5a49621-b25c-4684-aea8-8389f3a8afaf
  port: 8443
  server: 94.177.199.119
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 216.0
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/94.177.199.119=8443
- name: DK_speednode_0011
  network: ws
  password: 63b8ce6d-9a30-4122-a00f-fd47f020dc27
  port: 443
  server: 89.28.236.243
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 211.58
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
- name: ÁæéÂõΩ2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.57.238
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 200.96
  type: trojan
- flow: xtls-rprx-vision
  name: JP_speednode_0032
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: usa.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 183.08
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: SI_speednode_0048
  network: ws
  port: 443
  server: 45.144.52.23
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 176.03
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- flow: xtls-rprx-vision
  name: IQ_speednode_0030
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: ges.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 170.69
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: ÁæéÂõΩ3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4569
  server: us.wyau.cn
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 170.59
  type: trojan
- cipher: chacha20-ietf
  name: üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  password: asd123456
  port: 8388
  server: 103.149.183.80
  speed: 162.06
  type: ss
- name: PL_speednode_0038
  network: ws
  password: 55d19115-ec40-407b-a674-74e6a948347a
  port: 2053
  server: 45.144.48.55
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 159.7
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.55=2053
- name: IL_speednode_0021
  network: ws
  password: de763850-1022-4a03-a1ac-84422cfcd4fb
  port: 2053
  server: 77.91.69.238
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 154.25
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.91.69.238=2053
- name: NL_speednode_0037
  network: ws
  password: f5eaa93a-4660-46a8-a1fd-bf993c7da57c
  port: 8443
  server: 185.121.233.231
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 150.06
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/185.121.233.231=8443
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 149.68
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: RU_speednode_0043
  port: 4442
  reality-opts:
    public-key: HCkRC28M16WYrORNt2-Bga_3AuxuGnphlAwXHY9R4SI
    short-id: fd99
  server: 193.124.182.224
  servername: dl.google.com
  skip-cert-verify: false
  speed: 138.56
  tls: true
  type: vless
  udp: true
  uuid: 9429f5ce-ed0f-48e7-afda-12f7b23441af
- name: SI_speednode_0047
  network: ws
  port: 443
  server: fl-3-direct.djarbnet.ru
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 129.81
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- flow: xtls-rprx-vision
  name: IQ_speednode_0028
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: sws.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 126.05
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: È¶ôÊ∏Ø3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 443
  server: 58.152.110.216
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 125.28
  type: trojan
- name: Êó•Êú¨3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 202.181.103.235
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 116.42
  type: trojan
- name: Êó•Êú¨2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 1334
  server: 160.16.57.238
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 105.87
  type: trojan
- name: PL_speednode_0039
  network: ws
  password: 49d416e1-4cec-41e1-bff6-3748c466f275
  port: 8443
  server: 45.144.48.158
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 103.41
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.158=8443
proxy-groups:
- name: Ëá™Âä®ÈÄâÊã©
  proxies:
  - NL_speednode_0036
  - Êñ∞Âä†Âù°3|@ripaojiedian
  - IL_speednode_0020
  - üáØüáµ Êó•Êú¨4|@ripaojiedian
  - '@NoForcedheaven'
  - RU_speednode_0044
  - Êó•Êú¨|@ripaojiedian
  - SE_speednode_0046
  - IQ_speednode_0025
  - BG_speednode_0006
  - IT_speednode_0031
  - DK_speednode_0011
  - ÁæéÂõΩ2|@ripaojiedian
  - JP_speednode_0032
  - SI_speednode_0048
  - IQ_speednode_0030
  - ÁæéÂõΩ3|@ripaojiedian
  - üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  - PL_speednode_0038
  - IL_speednode_0021
  - NL_speednode_0037
  - MCI-IR--@V2rayAlpha-7
  - RU_speednode_0043
  - SI_speednode_0047
  - IQ_speednode_0028
  - È¶ôÊ∏Ø3|@ripaojiedian
  - Êó•Êú¨3|@ripaojiedian
  - Êó•Êú¨2|@ripaojiedian
  - PL_speednode_0039
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Ëá™Âä®ÈÄâÊã©
socks-port: 7891
