allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 295.69
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: LB_speednode_0012
  port: 443
  reality-opts:
    public-key: hnec5SxCD6Os-u0FNi_YS5CML1a_oWb0niZJ1mGuFBo
    short-id: 07e904766d29b958
  server: 77.110.119.225
  servername: st.ozone.ru
  skip-cert-verify: false
  speed: 287.99
  tls: true
  type: vless
  udp: true
  uuid: 4819860c-0e62-4804-9c59-967e5c2bed7a
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3093
  server: 160.16.150.76
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 267.25
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0001
  port: 26861
  reality-opts:
    public-key: IIdE2p3vqHDjHfLrvJXkrLoYpYMJH0R1tacCkHiDtAA
    short-id: ecc1c4
  server: shadowshaman.fonixapp.org
  servername: groww.in
  skip-cert-verify: false
  speed: 219.6
  tls: true
  type: vless
  udp: true
  uuid: 04db6938-72dc-42b4-a096-cc6a5e8316d2
- name: é¦™æ¸¯4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 157.85
  type: trojan
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 160.16.116.227
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 147.81
  type: trojan
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 134.37
  type: trojan
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.225
  speed: 110.01
  type: ss
- flow: xtls-rprx-vision
  name: AT_speednode_0004
  port: 31502
  reality-opts:
    public-key: oenAlMhG602prGwOqnAt5yZ55yuDEfZwGZXn-WaxizM
    short-id: e1814a
  server: silverzebra.fonixapp.org
  servername: marmiton.org
  skip-cert-verify: false
  speed: 106.98
  tls: true
  type: vless
  udp: true
  uuid: b20c12e7-f071-4829-94e7-17dc4e43a37a
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - '@V2rayNG3'
  - LB_speednode_0012
  - æ—¥æœ¬3|@ripaojiedian
  - AT_speednode_0001
  - é¦™æ¸¯4|@ripaojiedian
  - æ–°åŠ å¡2|@ripaojiedian
  - æ–°åŠ å¡3|@ripaojiedian
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - AT_speednode_0004
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
