allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.53
  speed: 290.59
  type: ss
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 257.84
  tls: false
  type: hysteria2
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 252.05
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: AT_speednode_0001
  port: 26861
  reality-opts:
    public-key: IIdE2p3vqHDjHfLrvJXkrLoYpYMJH0R1tacCkHiDtAA
    short-id: ecc1c4
  server: shadowshaman.fonixapp.org
  servername: groww.in
  skip-cert-verify: false
  speed: 248.96
  tls: true
  type: vless
  udp: true
  uuid: 04db6938-72dc-42b4-a096-cc6a5e8316d2
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.131.243
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 244.54
  type: trojan
- flow: xtls-rprx-vision
  name: LB_speednode_0011
  port: 443
  reality-opts:
    public-key: -Bdu8i-HU28Xmx87RMou5okYo8TqfbyZ8Ufs9RodUGE
    short-id: 097de35e52ec5256
  server: 77.110.127.105
  servername: st.ozone.ru
  skip-cert-verify: false
  speed: 208.65
  tls: true
  type: vless
  udp: true
  uuid: 72239cbc-5a25-411c-b4f5-b9167a10f5e1
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4054
  server: 153.121.76.9
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 206.8
  type: trojan
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2145
  server: 153.121.53.187
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 205.8
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 162.42
  tls: false
  type: hysteria2
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 16.162.87.79
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 159.18
  type: trojan
- flow: xtls-rprx-vision
  name: AT_speednode_0002
  port: 12645
  reality-opts:
    public-key: U15vYKJBiI0x1Sltv3qZrtuRoGlw5fIu-jlHfN1hBB4
    short-id: 3fd623
  server: graygoat.fonixapp.org
  servername: smallpdf.com
  skip-cert-verify: false
  speed: 155.28
  tls: true
  type: vless
  udp: true
  uuid: 8d5bca78-f49f-4e49-ad7b-bb58da44d40b
- name: é¦™æ¸¯4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 147.63
  type: trojan
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.131.243
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 130.56
  type: trojan
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 202.181.103.246
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 109.04
  type: trojan
- alterId: 2
  cipher: auto
  name: é¦™æ¸¯|@ripaojiedian
  network: ws
  port: '30809'
  server: v9.heduian.link
  servername: ''
  skip-cert-verify: false
  speed: 105.04
  tls: false
  type: vmess
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-opts:
    headers:
      Host: baidu.com
    path: /oooo
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - '@NoForcedheaven'
  - '@V2rayNG3'
  - AT_speednode_0001
  - æ—¥æœ¬2|@ripaojiedian
  - LB_speednode_0011
  - ç¾å›½|@ripaojiedian
  - æ—¥æœ¬|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - ç¾å›½3|@ripaojiedian
  - AT_speednode_0002
  - é¦™æ¸¯4|@ripaojiedian
  - ç¾å›½2|@ripaojiedian
  - æ—¥æœ¬3|@ripaojiedian
  - é¦™æ¸¯|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
