allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 127
  server: 160.16.116.227
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 289.61
  type: trojan
- name: IL_speednode_0006
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 45.144.172.243
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 289.59
  type: trojan
  udp: true
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4210
  server: 160.16.70.180
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 274.21
  type: trojan
- flow: xtls-rprx-vision
  name: GB_speednode_0005
  port: 443
  reality-opts:
    public-key: Mn0DIMKW6zu0_D3E1qKO7xMlIVZvB-rqO_-f7Le2vAs
    short-id: 428ef87fd47a3a32
  server: nl.nodes.rocketnetwork.ru
  servername: nl.nodes.rocketnetwork.ru
  skip-cert-verify: false
  speed: 271.47
  tls: true
  type: vless
  udp: true
  uuid: bccbecc9-c1d2-45d1-b3fa-771a19b9831c
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 270.23
  tls: false
  type: hysteria2
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4492
  server: 160.16.85.138
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 265.52
  type: trojan
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 233.55
  tls: false
  type: hysteria2
- name: CH_speednode_0001
  password: 019a8c1f-3d28-74e8-8a8e-40045d7ec77f
  port: 443
  server: 194.87.18.124
  skip-cert-verify: true
  sni: www.bilibili.com
  speed: 225.65
  type: trojan
  udp: true
- cipher: aes-256-cfb
  name: ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  port: 38388
  server: 103.186.154.225
  speed: 224.37
  type: ss
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2673
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 220.11
  type: trojan
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 3093
  server: 160.16.150.76
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 202.89
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 196.44
  tls: false
  type: hysteria2
- name: RU_speednode_0012
  network: ws
  port: 1443
  server: 81.161.98.228
  servername: cdn.filterai.ru
  skip-cert-verify: false
  speed: 190.76
  tls: true
  type: vless
  udp: true
  uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
  ws-opts:
    headers:
      Host: cdn.filterai.ru
    path: /websocketpl
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 170.03
  type: trojan
- name: é¦™æ¸¯4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 164.54
  type: trojan
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 5553
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 145.1
  type: trojan
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 1334
  server: 160.16.240.91
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 125.98
  type: trojan
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  port: 4211
  server: 160.16.70.180
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 107.19
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - æ–°åŠ å¡2|@ripaojiedian
  - IL_speednode_0006
  - ç¾å›½|@ripaojiedian
  - GB_speednode_0005
  - MCI-IR--@V2rayAlpha-14
  - æ—¥æœ¬|@ripaojiedian
  - '@NoForcedheaven'
  - CH_speednode_0001
  - ğŸ‡»ğŸ‡³ è¶Šå—|@ripaojiedian
  - æ–°åŠ å¡3|@ripaojiedian
  - æ—¥æœ¬3|@ripaojiedian
  - '@V2rayNG3'
  - RU_speednode_0012
  - é¦™æ¸¯5|@ripaojiedian
  - é¦™æ¸¯4|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  - æ—¥æœ¬2|@ripaojiedian
  - ç¾å›½2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
