allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: NL_speednode_0037
  network: ws
  password: f5eaa93a-4660-46a8-a1fd-bf993c7da57c
  port: 8443
  server: 185.121.233.231
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 287.01
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/185.121.233.231=8443
- name: Êó•Êú¨2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 1334
  server: 160.16.132.158
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 284.03
  type: trojan
- flow: xtls-rprx-vision
  name: US_speednode_0050
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 282.42
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: IQ_speednode_0025
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: frs.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 267.95
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: BG_speednode_0006
  port: 443
  reality-opts:
    public-key: ZmcE7f2ZycnrnsUSPkCrPBIGYC8dM4b27DX47DwCHXk
    short-id: 473915f2ef487f
  server: albania.solobot.ru
  servername: yahoo.com
  skip-cert-verify: false
  speed: 258.45
  tls: true
  type: vless
  udp: true
  uuid: 678bbdc1-7307-4cf2-bec1-bcdbd8efdbe5
- name: IT_speednode_0031
  network: ws
  password: d5a49621-b25c-4684-aea8-8389f3a8afaf
  port: 8443
  server: 94.177.199.119
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 252.19
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/94.177.199.119=8443
- name: È¶ôÊ∏Ø5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.77.239.35
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 252.07
  type: trojan
- name: IL_speednode_0021
  network: ws
  password: de763850-1022-4a03-a1ac-84422cfcd4fb
  port: 2053
  server: 77.91.69.238
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 251.49
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.91.69.238=2053
- name: NL_speednode_0036
  network: ws
  password: 5ad5fe82-6b60-4f59-977b-93910ef7a9ca
  port: 443
  server: 86.107.197.239
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 233.04
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/86.107.197.239=443
- name: ÁæéÂõΩ3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4094
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 221.05
  type: trojan
- name: SE_speednode_0046
  network: ws
  password: edeff73d-065d-4b0a-b848-aad9d3380223
  port: 443
  server: 77.221.141.207
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 220.43
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.221.141.207=443
- client-fingerprint: firefox
  flow: xtls-rprx-vision
  name: LU_speednode_0033
  port: 17715
  reality-opts:
    public-key: itR04_u2Xo8xZ4a9Kk2U-pul4hNXzZYskdHdx4rjO0s
    short-id: 0db891a2
  server: ezalor.fonixapp.org
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 220.38
  tls: true
  type: vless
  udp: true
  uuid: 9627bc06-1a36-4674-aeb8-4e863b8bd979
- name: È¶ôÊ∏Ø4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 203.198.122.97
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 201.2
  type: trojan
- flow: xtls-rprx-vision
  name: IQ_speednode_0030
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: ges.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 196.53
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: IQ_speednode_0028
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: sws.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 191.71
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- cipher: chacha20-ietf
  name: üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  password: asd123456
  port: 8388
  server: 103.149.182.158
  speed: 190.39
  type: ss
- name: PL_speednode_0039
  network: ws
  password: 49d416e1-4cec-41e1-bff6-3748c466f275
  port: 8443
  server: 45.144.48.158
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 188.71
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.158=8443
- name: HK_speednode_0019
  password: BxceQaOe
  port: 443
  server: 203.198.122.97
  skip-cert-verify: true
  sni: t.me/ripaojiedian
  speed: 142.92
  type: trojan
  udp: true
- name: Êñ∞Âä†Âù°|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 2760
  server: 160.16.81.84
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 131.27
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0043
  port: 4442
  reality-opts:
    public-key: HCkRC28M16WYrORNt2-Bga_3AuxuGnphlAwXHY9R4SI
    short-id: fd99
  server: 193.124.182.224
  servername: dl.google.com
  skip-cert-verify: false
  speed: 129.87
  tls: true
  type: vless
  udp: true
  uuid: 9429f5ce-ed0f-48e7-afda-12f7b23441af
- flow: xtls-rprx-vision
  name: AT_speednode_0003
  port: 20579
  reality-opts:
    public-key: mT6lh-gtbEuWk3Zk6XGF_hYvpLwxTyvwtH7F-_fRbxI
    short-id: 89f1da93
  server: 152.53.84.101
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 129.85
  tls: true
  type: vless
  udp: true
  uuid: 93cd7e0f-8a81-4076-be8b-6d3bf3f8f810
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 126.05
  tls: false
  type: hysteria2
- name: RU_speednode_0042
  port: 58871
  reality-opts:
    public-key: J4NvMlw9Hue3ELYmxP4HQXJ71tf2BAIhOLSyIRkNekA
    short-id: 05aa79ca512b2a58
  server: 81.177.214.214
  servername: yandex.ru
  skip-cert-verify: false
  speed: 105.61
  tls: true
  type: vless
  udp: true
  uuid: 74973884-76d6-4e51-a20f-c15b0acaf1d3
- name: Êñ∞Âä†Âù°2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5553
  server: 160.16.124.55
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 104.94
  type: trojan
proxy-groups:
- name: Ëá™Âä®ÈÄâÊã©
  proxies:
  - NL_speednode_0037
  - Êó•Êú¨2|@ripaojiedian
  - US_speednode_0050
  - IQ_speednode_0025
  - BG_speednode_0006
  - IT_speednode_0031
  - È¶ôÊ∏Ø5|@ripaojiedian
  - IL_speednode_0021
  - NL_speednode_0036
  - ÁæéÂõΩ3|@ripaojiedian
  - SE_speednode_0046
  - LU_speednode_0033
  - È¶ôÊ∏Ø4|@ripaojiedian
  - IQ_speednode_0030
  - IQ_speednode_0028
  - üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  - PL_speednode_0039
  - HK_speednode_0019
  - Êñ∞Âä†Âù°|@ripaojiedian
  - RU_speednode_0043
  - AT_speednode_0003
  - '@NoForcedheaven'
  - RU_speednode_0042
  - Êñ∞Âä†Âù°2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Ëá™Âä®ÈÄâÊã©
socks-port: 7891
