allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 18.163.122.76
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 284.25
  type: trojan
- name: 'ğŸ”·ğŸ†”@v2ray_configs_poolğŸ”· #58'
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: tokyo.nezhasu.com
  skip-cert-verify: true
  sni: Tokyo.nezhasu.com
  speed: 275.55
  tls: false
  type: hysteria2
- name: NL_speednode_0004
  network: ws
  password: e812343b-61a1-46fd-b086-b1395d0eb7de
  port: 443
  server: 89.110.116.141
  skip-cert-verify: false
  sni: joss.gpj.web.id
  speed: 262.3
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj.web.id
    path: /Free-VPN-CF-Geo-Project/89.110.116.141=443
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.151.196
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 255.11
  type: trojan
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 160.16.151.196
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 188.25
  type: trojan
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 161.33
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 3.112.229.1
  speed: 156.88
  type: ss
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 141.67
  tls: false
  type: hysteria2
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 153.121.65.107
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 121.89
  type: trojan
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 160.16.63.16
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 119.31
  type: trojan
- name: RU_speednode_0005
  network: ws
  password: 3b38715b-f08a-46dd-9904-7531ca4bb6e8
  port: 2053
  server: 95.182.120.208
  skip-cert-verify: false
  sni: joss.gpj.web.id
  speed: 117.63
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj.web.id
    path: /Free-VPN-CF-Geo-Project/95.182.120.208=2053
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 153.121.65.107
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 101.63
  type: trojan
- name: HK_speednode_0003
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 101.39
  type: trojan
  udp: true
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - ç¾å›½3|@ripaojiedian
  - 'ğŸ”·ğŸ†”@v2ray_configs_poolğŸ”· #58'
  - NL_speednode_0004
  - ç¾å›½2|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  - é¦™æ¸¯5|@ripaojiedian
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - '@V2rayNG3'
  - æ—¥æœ¬2|@ripaojiedian
  - æ—¥æœ¬3|@ripaojiedian
  - RU_speednode_0005
  - æ–°åŠ å¡2|@ripaojiedian
  - HK_speednode_0003
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
