allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: HK_speednode_0003
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 292.55
  type: trojan
  udp: true
- alpn:
  - h2
  flow: xtls-rprx-vision
  name: GB_speednode_0002
  port: 443
  reality-opts:
    public-key: ckRcueERkPqqjZABwxqni_J_Nbb70Q6k5fEEUAjoImw
  server: 217.154.218.42
  servername: azure.com
  skip-cert-verify: false
  speed: 276.88
  tls: true
  type: vless
  udp: true
  uuid: 0b0b98be-fdaf-40cc-a953-cc4091c838e1
- name: ç¾å›½|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 2890
  server: 160.16.63.16
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 265.42
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 3.112.229.1
  speed: 259.6
  type: ss
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 160.16.63.16
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 251.3
  type: trojan
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 160.16.151.196
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 248.06
  type: trojan
- name: NL_speednode_0004
  network: ws
  password: e812343b-61a1-46fd-b086-b1395d0eb7de
  port: 443
  server: 89.110.116.141
  skip-cert-verify: false
  sni: joss.gpj.web.id
  speed: 245.52
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj.web.id
    path: /Free-VPN-CF-Geo-Project/89.110.116.141=443
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.151.196
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 238.01
  type: trojan
- name: 'ğŸ”·ğŸ†”@v2ray_configs_poolğŸ”· #58'
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: tokyo.nezhasu.com
  skip-cert-verify: true
  sni: Tokyo.nezhasu.com
  speed: 237.33
  tls: false
  type: hysteria2
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 224.2
  tls: false
  type: hysteria2
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 216.36
  tls: false
  type: hysteria2
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 174.79
  tls: false
  type: hysteria2
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2173
  server: 18.163.122.76
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 148.56
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 59.125.62.188
  speed: 134.68
  type: ss
- name: RU_speednode_0005
  network: ws
  password: 3b38715b-f08a-46dd-9904-7531ca4bb6e8
  port: 2053
  server: 95.182.120.208
  skip-cert-verify: false
  sni: joss.gpj.web.id
  speed: 123.78
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.gpj.web.id
    path: /Free-VPN-CF-Geo-Project/95.182.120.208=2053
- flow: xtls-rprx-vision
  name: BG_speednode_0001
  port: 8443
  reality-opts:
    public-key: aILMLxhAsgJvx7TY3EsxOdmIc1uB0V7aJVIXaKYPPk4
    short-id: 05a8b9980e65114c
  server: de.monkeyisland.life
  servername: de.monkeyisland.life
  skip-cert-verify: false
  speed: 105.79
  tls: true
  type: vless
  udp: true
  uuid: df5fc3f7-6b01-489a-a73c-e1297b14a3dd
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - HK_speednode_0003
  - GB_speednode_0002
  - ç¾å›½|@ripaojiedian
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - æ—¥æœ¬3|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  - NL_speednode_0004
  - ç¾å›½2|@ripaojiedian
  - 'ğŸ”·ğŸ†”@v2ray_configs_poolğŸ”· #58'
  - MCI-IR--@V2rayAlpha-14
  - '@V2rayNG3'
  - '@NoForcedheaven'
  - ç¾å›½3|@ripaojiedian
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - RU_speednode_0005
  - BG_speednode_0001
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
