allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 298.36
  tls: false
  type: hysteria2
- name: 新加坡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5552
  server: 160.16.236.32
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 282.73
  type: trojan
- name: 日本|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 1924
  server: 160.16.227.93
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 243.69
  type: trojan
- name: RU_speednode_0016
  network: ws
  password: -4146XJHYAzJ4K8Ov6_LBQ
  port: 11000
  server: 194.35.116.62
  skip-cert-verify: false
  sni: f4e23c6c168f0e91.noproblemvpn.ru
  speed: 219.35
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: f4e23c6c168f0e91.noproblemvpn.ru
    path: /tw
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 202.2
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: SG_speednode_0019
  port: 46920
  reality-opts:
    public-key: 26jcWQerQE3ryBAm1OCcC7MrgGlI5I-gpdel1xf2Hx8
  server: 43.160.246.221
  servername: aws.amazon.com
  skip-cert-verify: false
  speed: 185.06
  tls: true
  type: vless
  udp: true
  uuid: 33a0c07b-82c7-40c8-aac7-4ab2071bcc03
- flow: xtls-rprx-vision
  name: US_speednode_0023
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: fis.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 173.85
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- client-fingerprint: firefox
  name: DE_speednode_0002
  port: 9107
  reality-opts:
    public-key: Go_wk-NFoenM3xuCSQ84_0Lzh3Y6XrHzTz8XTbQl8lI
    short-id: e8ef8df79e4a6343
  server: 195.254.165.152
  servername: refersion.com
  skip-cert-verify: false
  speed: 172.57
  tls: true
  type: vless
  udp: true
  uuid: 774727ed-1e56-41bd-b55f-28549e21bcc8
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 171.5
  tls: false
  type: hysteria2
- name: 香港3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 443
  server: 58.152.110.216
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 139.98
  type: trojan
- name: 美国2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.57.238
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 132.27
  type: trojan
- name: 日本3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 202.181.103.235
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 120.15
  type: trojan
proxy-groups:
- name: 自动选择
  proxies:
  - '@V2rayNG3'
  - 新加坡|@ripaojiedian
  - 日本|@ripaojiedian
  - RU_speednode_0016
  - '@NoForcedheaven'
  - SG_speednode_0019
  - US_speednode_0023
  - DE_speednode_0002
  - MCI-IR--@V2rayAlpha-7
  - 香港3|@ripaojiedian
  - 美国2|@ripaojiedian
  - 日本3|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
